[package]
name    = "mcaselector-lite"
version = "0.0.1"
edition = "2024"

[lib]
crate-type = ["staticlib"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
glfw-sys = "5.0.0"
libc = "0.2.171"
