# Copyright (C)2026 mcxedit
# Licensed under GPL-2.0-only. For further information,
# view `git log`, and the COPYING and CONTRIBUTORS files
# at www.github.com/thepigeongenerator/mcxedit.
SHELL = /bin/sh
.SUFFIXES:

# Include persistent user configurations.
-include .config.mk

# Binary & versioning information
# NAME exists because Windows_NT.mk appends ".exe", because yup.
NAME    = mcxedit
VERSION = 0.0

# Flags, including the flag in the definition so it may be overridden.
# Generally speaking, anything prior to the recursive reference of the variable
# is able to be overridden, anything afterwards is applied no matter what.
CPPFLAGS := -DNDEBUG -U_GNU_SOURCE ${CPPFLAGS}
CFLAGS   := -O2 ${CFLAGS} -g -std=gnu17\
	    -Wall -Wextra -Wpedantic -Wno-pointer-arith -Wvla
LDFLAGS  := -flto ${LDFLAGS}
LDLIBS   := ${LDLIBS} -lm -larchive

PREFIX = /usr/local
BINDIR = ${prefix}/bin

# Locate the source files
SRC := $(shell find src/ -name '*.c' -print)
OBJ := $(addsuffix .o,${SRC})
DEP := $(addsuffix .d,${SRC})

# Set Q to @ to silence commands being printed, unless --no-silent has been set
ifeq (0, $(words $(findstring --no-silent,${MAKEFLAGS})))
msg=@printf ' %-8s %s\n' "${1}" "${2}"
Q=@
else
msg=
Q=
endif

# Detect whether we're compiling on Windows, meaning
# a lot of things considered "standard" are unavailable.
ifeq (${OS},Windows_NT)
include Windows_NT.mk
endif

# ==================== #
#   Rule Definitions   #
# ==================== #
PHONY = all
all: ${NAME}

# CLEANING
clean:
	${Q}find src/ \( -name '*.o' -o -name '*.d' \) -exec rm {} \;
	${Q}find ./ -name '*.gz' -exec rm {} \;
PHONY += clean

# SEMANTIC CHECKING
check:; ${Q}sparse ${CPPFLAGS} ${CFLAGS} ${SRC}
PHONY += check

# INSTALLATION
install: all | ${DESTDIR}${bindir}/
	$(call msg,INSTALL,${NAME})
	${Q}install -m0755 ${NAME} ${DESTDIR}${bindir}
uninstall:
	rm ${DESTDIR}${bindir}/${NAME}
PHONY += install uninstall

# GENERATING TRACKED FILES
CONTRIBUTORS:
	${Q}printf "# Generated by \`make $@\`, if editing manually, keep it sorted.\n" >CONTRIBUTORS~
	${Q}printf "# List of all contributors of the project:\n" >>CONTRIBUTORS~
	${Q}git log --format='%aN <%aE>%n%cN <%cE>' | sort -u >>CONTRIBUTORS~
	${Q}mv CONTRIBUTORS~ CONTRIBUTORS
PHONY += CONTRIBUTORS

#
# COMPILATION
#
${NAME}: ${OBJ}
	$(call msg,LD,$@)
	${Q}${CC} ${LDFLAGS} ${LDLIBS} -o $@ $^
%.c.o: %.c
	$(call msg,CC,$@)
	${Q}${CC} -c ${CPPFLAGS} ${CFLAGS} -o $@ $<

#
# GENERAL UTILITY
#
%.gz: %
	$(call msg,GZIP,$@)
	${Q}gzip -fk $<
%/:
	$(call msg,MKDIR,$@)
	${Q}mkdir -p $@

# Generate and include dependencies,
# ignoring any errors that may occur when doing so.
%.c.d: %.c; ${Q}${CC} -MM ${CPPFLAGS} -MF $@ $<
ifeq (0, $(words $(findstring ${MAKECMDGOALS}, clean)))
-include ${DEP}
endif

# Apply rules added to PHONY as phony rules.
# They are not checked against files.
.PHONY: ${PHONY}
