name: lint
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
jobs:
  exec-lint:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/thepigeongenerator/mcaselector-lite:latest
    steps:
      # TODO: add linting checking here
      - run: echo "TODO"

