name: tests
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
jobs:
  execute-tests:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/thepigeongenerator/mcaselector-lite:latest
    strategy:
      matrix:
        arch:
          - linux-x86_64
          - win-x86_64
    steps:
      # TODO: add unit test job here
      - run: echo "TODO"
