name: release
on:
  push:
    branches:
      - dev
      - $default-branch
  pull_request:
    branches:
      - dev
      - $default-branch
jobs:
  tmp:
    runs-on: ubuntu-latest
    steps:
      - run: echo Hello, World
